### ISSUE TITLE
Got 400 Bad Request

### ISSUE THREAD

**Issue by junyu-w** [smilli/makethisinanhour#5]
Hi I followed your steps but I got 400 Bad Request when I tried to access the website. https://www.dropbox.com/s/824gq11hb0b7p16/Screenshot%202015-03-30%2001.30.33.png?dl=0
this is what I got after saving changes after the last step, did I do something wrong?

**Comment by smilli** [comment]
Looks like you got it working?

**Comment by junyu-w** [comment]
Yea maybe it's just the changes were not updated at that time...and btw do I have to use that specific ip address in the instruction or I have to use my own ip address? Thanks :)

**Comment by smilli** [comment]
Yeah those ip addresses are Github's.  See https://help.github.com/articles/tips-for-configuring-an-a-record-with-your-dns-provider/ for details
